.gitignore, .npmignore, .travis.yml, README.md, package.json
added travis build and istanbul coverage
=> build tools

lib/cookie/tokenV1.js, lib/cookie/tokenV3.js, lib/pxapi.js, lib/pxconfig.js, lib/pxcontext.js, lib/pxcookie.js, lib/pxoriginaltoken.js, test/unit.test.js
1) updated pxcookie to better handle special mobile tokens
=> EN-5175 Better handling of mobile special tokens

.gitignore, lib/configloader.js, lib/pxapi.js, lib/pxclient.js, lib/pxconfig.js, lib/pxenforcer.js, lib/pxproxy.js, lib/request.js, lib/templates/block.mustache, lib/templates/funcaptcha.mustache, lib/templates/recaptcha.mustache, package.json, test/unit.test.js
1) Added support for first party mode
=> EN-5107 Added first party support

lib/pxclient.js, lib/pxcontext.js, lib/pxutil.js
1) Refactored sensitive header filtering to be case-insensitive
2) added filteredHeaders property to pxcontext for the automated tests
=> EN-5609 Headers related fixes

lib/pxapi.js, lib/pxenforcer.js
1) Added risk_mode to risk API calls
2) Added simulated_block for activity type
=> APP-275 Added simulated_block and risk_mode

lib/pxapi.js, lib/pxconfig.js
1) Added config option enrich_custom_parameters
=> APP-276 - Added support for enrich_custom_parameters

lib/pxcontext.js
1) Added a try/catch for ip headers extraction.
=> APP-279 Empty ip_headers property fix

.eslintrc.js, CHANGELOG.md, README.md, lib/pxconfig.js, lib/pxenforcer.js, package.json, test/pxenforcer.test.js
=> [ADD] advanded blocking response.

.travis.yml, CHANGELOG.md, README.md, lib/configloader.js, lib/pxapi.js, lib/pxconfig.js, lib/pxenforcer.js, lib/pxhttpc.js, lib/pxutil.js, lib/telemetry_handler.js, package-lock.json, package.json
* fixed timeout error, lint fixes
* removed node 11 from tests because it turned EOL
=> fix timeout error (#96)

CHANGELOG.md, lib/pxapi.js, lib/pxclient.js, lib/pxcontext.js, lib/pxenforcer.js
2) fixed bug - send pxhd to collector at block activity
3) fixed bug - set pxhd expiration
=> 1)do not echo back pxhd cookie coming from client

CHANGELOG.md, README.md, lib/pxclient.js, lib/pxconfig.js, lib/pxenforcer.js, package-lock.json, package.json
* Added support for external activities
* updated dependencies
External activities are a way to send page_requested on the response object (viewer-response for lambda) so it will consist of the status code as well.
=> Version 2.7.0

CHANGELOG.md, README.md, lib/pxconfig.js, lib/pxenforcer.js, lib/pxutil.js, package.json, test/pxenforcer.test.js
* Added support for regex in filter by user agent
=> Version 2.11.0

.prettierrc, CHANGELOG.md, README.md, lib/pxapi.js, lib/pxcontext.js, lib/pxcookie.js, lib/pxdataenrichment.js, lib/pxenforcer.js, lib/pxpayload.js, lib/pxutil.js, package.json
* Added support for PXDE
* small refactor
* Version 2.12.0
* pxcontext: changed cookie assignment order
Co-authored-by: Ori Gold <ori.gold@perimeterx.com>
=> Version 2.12.0

CHANGELOG.md, README.md, package-lock.json, package.json
=> release v2.13.0

lib/pxcontext.js, lib/pxoriginaltoken.js, lib/pxutil.js
Link to Jira: https://perimeterx.atlassian.net/browse/SDKNEW-930
=> Drop Token version number from original token field.

lib/enums/CookieOrigin.js, lib/pxapi.js, lib/pxcontext.js, lib/pxcookie.js, lib/pxenforcer.js, lib/pxhttpc.js, test/pxenforcer.test.js
passes all page_requested_activity tests
=> Spec alignment/page requested activity

CHANGELOG.md, LICENSE, README.md, index.js, lib/pxconfig.js, package.json, test/pxconfig.test.js
* aligning configs to spec
https://perimeterx.atlassian.net/browse/SDKNEW-1060
=> release v3.0.0

test/pxenforcer.test.js
Reverts PerimeterX/perimeterx-node-core#206
=> Revert "enforced routes unit tests fixed to match spec"

lib/pxenforcer.js, lib/pxutil.js
Reverts PerimeterX/perimeterx-node-core#197
=> Revert "enforced routes bug fix"

lib/pxapi.js, lib/pxutil.js
https://perimeterx.atlassian.net/browse/SDKNEW-1030
https://perimeterx.atlassian.net/browse/SDKNEW-1275
=> can bypass monitored route with header

CHANGELOG.md, README.md, package.json
=> release v3.2.1

CHANGELOG.md, README.md, package.json
=> Release to dev version 3.3.0

lib/templates/block_template.mustache
Bug fix - cssRef injection to html.
=> Release 3.3.0 to dev(bug fix)- v3.3.0

lib/templates/block_template.mustache
Fix bug (cssRef injection to html) to version 3.3.0.
=> Release 3.3.0 to master (bug fix)- v3.3.0

CHANGELOG.md, README.md, package.json
=> Release to master v3.3.1

CHANGELOG.md, README.md, package.json
=> Release to dev V3.3.1

CHANGELOG.md, README.md, lib/templates/block_template.mustache, package.json
Fixed - URLs with query params did not render properly on new block page
=> Hotfix/block-page-url-rendering - release v3.3.2

lib/pxutil.js
https://perimeterx.atlassian.net/browse/SDKNEW-1961
=> [SDKNEW-1961] parse body from string to object if needed

CHANGELOG.md, README.md, package.json
Description: Fixed GraphQL - parsed operation name issue
=> [Release] Version 3.4.2

CHANGELOG.md, lib/pxenforcer.js
Description:
Set pxhd with SameSite=Lax
=> SDKNEW-1684 [Feature] PXHD SameSite issue

CHANGELOG.md, lib/pxconfig.js, lib/pxenforcer.js, test/pxenforcer.test.js
https://perimeterx.atlassian.net/browse/SDKNEW-2468
https://perimeterx.atlassian.net/browse/SDKNEW-2473
* New custom function called `px_modify_context` which allows the customer to make modifications immediately after the context is created
* This allows for custom logic dictating whether requests should be in monitored / enforced / sensitive
=> [SDKNEW-2468] Feature/modify context

CHANGELOG.md, README.md, package-lock.json, package.json
https://perimeterx.atlassian.net/browse/SDKNEW-2473
=> [SDKNEW-2473] release v3.6.0 (to dev)

lib/pxenforcer.js
in case a header has spaces between the commas - the current condition wont work and the enforcer will return an HTML response instead of json.
=> added trim to accept header value condition

lib/pxconfig.js, lib/pxcontext.js, lib/pxcookie.js, lib/pxutil.js, test/graphql.test.js, test/pxenforcer.test.js
Added custom sensitive request function and change graphQL functionality to support graphQL body with no query
https://perimeterx.atlassian.net/browse/SDKNEW-2740
=> Added custom sensitive request function and change graphQL functionality to support graphQL body with no query

lib/pxcontext.js, lib/utils/constants.js
Added custom cookie header support
=> [SDKNEW-2873]custom cookie header support

CHANGELOG.md, lib/pxclient.js, lib/pxconfig.js, lib/pxhttpc.js, lib/pxproxy.js, lib/templates/block_template.mustache
=> Added timeout to first-party requests
